HastaneProjesi/Models/Appointment.cs
using System.ComponentModel.DataAnnotations;

namespace HastaneProjesi.Models
{
    public class Appointment
    {
        [Key]
        public int AppointmentID { get; set; }


        [Required(ErrorMessage = "Username is required")]
        [StringLength(30, ErrorMessage = "Username can be max 30 characters")]
        public string UserName { get; set; } 


       
        [Required(ErrorMessage = "Clinic is required")]
        
        public string ClinicID { get; set; }

        [Required(ErrorMessage = "Doctor is required")]

        public string DoctorID { get; set; }


        [Required(ErrorMessage ="Date and Time is required")]
        public DateTime SelectedDate { get; set; }
        
    }
}

HastaneProjesi/Controllers/AppointmentController.cs
using HastaneProjesi.Migrations;
using HastaneProjesi.Models;
using HastaneProjesi.Repositories;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace HastaneProjesi.Controllers
{
    public class AppointmentController : Controller
    {
        Context c = new Context();

        AppointmentRepository appointmentRepository = new AppointmentRepository();

        [Authorize(Roles = "user,admin")]
        public IActionResult MyAppointments()

        {
            return View(appointmentRepository.AppointmentList());
        }

        [Authorize(Roles ="admin")]
        public IActionResult AllAppointments()

        {
            return View(appointmentRepository.AppointmentList());
        }

        public IActionResult AppointmentGet(int id)
        {
            var x = appointmentRepository.GetAppointment(id);
            Appointment cln = new Appointment()
            {
                UserName = x.UserName,
                ClinicID = x.ClinicID,
                DoctorID = x.DoctorID,
                SelectedDate = x.SelectedDate
            };
            return View(cln);
        }

        public IActionResult AppointmentUpdate(Appointment p)
        {
            var x = appointmentRepository.GetAppointment(p.AppointmentID);
            x.UserName = p.UserName;
            x.ClinicID = p.ClinicID;
            x.DoctorID = p.DoctorID;
            x.SelectedDate = p.SelectedDate;
            appointmentRepository.AppointmentUpdate(x);
            return RedirectToAction("Index", "Patient");
        }

        public IActionResult AppointmentDelete(int id)
        {
            var x = appointmentRepository.GetAppointment(id);
            appointmentRepository.AppointmentUpdate(x);
            return RedirectToAction("Index", "Patient");

        }



        [Authorize(Roles = "user,admin")]
        [HttpGet]
        public IActionResult MakeAnAppointment()
        {     
			List<Clinic> clinics = c.Clinics.ToList();
            ViewBag.ListClinics = new SelectList(clinics, "ClinicID", "ClinicName");

			return View();
        }
        [HttpPost]
        public IActionResult GetDoctorByClinic(int clinicID)
        {
            List<Doctor> doctors = new List<Doctor>();
            doctors = c.Doctors.Where(e => e.ClinicID == clinicID).ToList();
            SelectList DoctorList = new SelectList(doctors,"DoctorID","DoctorName");
            return Json(DoctorList);
        }
        [Authorize(Roles = "user,admin")]
        [HttpPost]
        public IActionResult MakeAnAppointment(Appointment p)
        {
           

            AppointmentRepository appointmentRepository = new AppointmentRepository();

            appointmentRepository.AppointmentAdd(p);
            return RedirectToAction("Index", "Home");
        }

        public string GetClinicName(int clinicID)
        {
           
            var clinic = c.Clinics.FirstOrDefault(c => c.ClinicID == clinicID);
            return clinic != null ? clinic.ClinicName : "N/A";
        }
    }
}

HastaneProjesi/Views/Appointment/AllAppointments.cshtml
@model List<HastaneProjesi.Models.Appointment>
@{
    ViewData["Title"] = "MyAppointments";
    Layout = "~/Views/Shared/_UserLayout.cshtml";
}

<h2>My Appointments</h2>
<br />
<table class="table table-bordered">
    <tr>
        <th>ID</th>
        <th>User Name</th>
        <th>Clinic Name</th>
        <th>Doctor Name</th>
        <th>Selected Date</th>
       
    </tr>
    @foreach (var x in Model)
    {
        <tr>
            <td>@x.AppointmentID</td>
            <td>@x.UserName</td>
            <td>@x.ClinicID</td>
            <td>@x.DoctorID</td>
            <td>@x.SelectedDate</td>
           

        </tr>
    }
</table>

HastaneProjesi/Views/Appointment/MakeAnAppointment.cshtml
@model HastaneProjesi.Models.Appointment
@{
    ViewData["Title"] = "MakeAnAppointment";
    Layout = "~/Views/Shared/_UserLayout.cshtml";
}


<div class="row">
    <div class="col-lg-9 mx-auto rounded border p-3">
        <h2 class="text-center mb-5">Appointment</h2>

        <form method="post">
            <div class="row mb-3">
                <label class="col-sm-4 col-form-label">User Name: </label>
                <div class="col-sm-8">
                    <input class="form-control" asp-for="UserName" value="@User.Identity.Name" readonly />
                </div>
            </div>

            <div class="row mb-3">
                <label class="col-sm-4 col-form-label">Clinic ID: </label>
                          
                  
                    <div class="col-sm-8">
                        <select class="dropdown-item-text" asp-for="ClinicID" asp-items="ViewBag.ListClinics" onchange="GetDoctors(this.value)"> </select>
                        <span asp-validation-for="ClinicID" class="text-danger"></span>
                    </div>
                
            </div>
            

            <div class="row mb-3">
                <label class="col-sm-4 col-form-label">Doctor ID: </label>
                <div class="col-sm-8">
                    <select class="form-control" name="DoctorID" asp-for="DoctorID" > </select>
                    <span asp-validation-for="DoctorID" class="text-danger"></span>
                </div>
            </div>
            <script>
                      function GetDoctors(clinicID) {
                          var procemessage = "<option value= '0'>wait....</option>";
                          $("#DoctorID").html(procemessage).show();
                          var url = '@Url.Action("GetDoctorByClinic","Appointment")';
                          $.ajax({
                              url: url,
                              data: { ClinicID: clinicID },
                              cache: false,
                              type: "POST",
                              success: function (data) {
                                  var markup = "<option value= '0'>........</option>"
                                  for (var x = 0; x < data.length; x++) {
                                      markup += '<option value"' + data[x].value + '">' + data[x].text + '</option>';
                                  }
                                  $("#DoctorID").html(markup).show();
                              },
                              error: function (response) {
                                  alert("error:" + response);
                              }
                          });
                      }
            </script>

            <div class="row mb-3">
                <label class="col-sm-4 col-form-label">Selected Date: </label>
                <div class="col-sm-8">
                    <input class="form-control" asp-for="SelectedDate" />
                    <span asp-validation-for="SelectedDate" class="text-danger"></span>
                </div>
            </div>

            

            <div class="row">
                <div class="offset-sm-4" col-sm-8>
                    <button type="submit" class="btn btn-primary">Submit</button>
                </div>
            </div>
        </form>
    </div>
</div>

HastaneProjesi/Views/Appointment/MyAppointments.cshtml
@model List<HastaneProjesi.Models.Appointment>
@{
    ViewData["Title"] = "MyAppointments";
    Layout = "~/Views/Shared/_UserLayout.cshtml";
}

<h2>My Appointments</h2>
<br />
<table class="table table-bordered">
    <tr>
        <th>ID</th>
        <th>User Name</th>
        <th>Clinic Name</th>
        <th>Doctor Name</th>
        <th>Selected Date</th>
        <th>Delete</th>
    </tr>
    @foreach (var x in Model)
    {
        <tr>
            <td>@x.AppointmentID</td>
            <td>@x.UserName</td>
            <td>@x.ClinicID</td>
            <td>@x.DoctorID</td>
            <td>@x.SelectedDate</td>
            <td><a href="/Appointment/AppointmentDelete/@x.AppointmentID" class="btn btn-danger">Delete</a></td>

        </tr>
    }
</table>