HastaneProjesi/Models/Clinic.cs
using HastaneProjesi.Models;
using System.ComponentModel.DataAnnotations;
using System.Collections.Generic;


namespace HastaneProjesi.Models
{
    public class Clinic
    {
        [Key]
        public int ClinicID { get; set; }

        [Required(ErrorMessage ="Clinic name not empty!!!")]
        public string ClinicName { get; set; }
        public string ClinicDescription { get; set; }  
        public bool Status { get; set; }
        public List<Doctor> Doctors { get; set; }

    }
}

HastaneProjesi/Controllers/ClinicController.cs
using HastaneProjesi.Repositories;
using Microsoft.AspNetCore.Mvc;
using HastaneProjesi.Models;
using Microsoft.Identity.Client;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc.Authorization;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Identity;

namespace HastaneProjesi.Controllers
{
	
	[Authorize(Roles ="admin")]
    public class ClinicController : Controller
    {
        ClinicRepository clinicRepository = new ClinicRepository();
        
        
        public IActionResult Index()
        {
            
            return View(clinicRepository.ClinicList());   
        }
        [HttpGet]
        public IActionResult ClinicAdd()
            {
                return View();
            }
        [HttpPost]
        public IActionResult ClinicAdd(Clinic p)
        {
           // if (!ModelState.IsValid)
           // {
             //   return View("ClinicAdd");
            //}
            clinicRepository.ClinicAdd(p);
            return RedirectToAction("Index");
        }
        public IActionResult ClinicGet(int id)
        {
            var x = clinicRepository.GetClinic(id);
            Clinic cln = new Clinic()
            {
                ClinicName = x.ClinicName,
                ClinicDescription = x.ClinicDescription,
                ClinicID = x.ClinicID,     
                Status = x.Status
            };
            return View(cln);
        }
        [HttpPost]
        public IActionResult ClinicUpdate(Clinic p)
        {
            var x = clinicRepository.GetClinic(p.ClinicID);
            x.ClinicName = p.ClinicName;
            x.ClinicDescription = p.ClinicDescription;
            x.Status = p.Status;
            clinicRepository.ClinicUpdate(x);
            return RedirectToAction("Index");
        }
        
        public IActionResult ClinicDelete(int id)
        {
            var x = clinicRepository.GetClinic(id);
            x.Status = false;
            clinicRepository.ClinicUpdate(x);
            return RedirectToAction("Index");

        }

        
    }
}

HastaneProjesi/Views/Clinic/ClinicAdd.cshtml
@model HastaneProjesi.Models.Clinic
@{
    ViewData["Title"] = "ClinicAdd";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Clinic Add Page</h2>
<br />
@using (Html.BeginForm("ClinicAdd", "Clinic", FormMethod.Post)) 
{
    @Html.LabelFor(x=>x.ClinicName)
    @Html.TextBoxFor(x=>x.ClinicName, new { @class = "form-control" })
    @Html.ValidationMessageFor(x=>x.ClinicName,"",new { @style="color:red"})
    <br />
    <br />
    @Html.LabelFor(x=>x.ClinicDescription)
    @Html.TextBoxFor(x=>x.ClinicDescription, new { @class = "form-control" })
    <br />
    <button class="btn btn-info">Save</button>
}

HastaneProjesi/Views/Clinic/ClinicGet.cshtml
@model HastaneProjesi.Models.Clinic
@{
    ViewData["Title"] = "ClinicGet";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Clinic Get Page</h2>
<br />
@using (Html.BeginForm("ClinicUpdate", "Clinic", FormMethod.Post))
{
    @Html.LabelFor(x=>x.ClinicID)
    @Html.TextBoxFor(x=>x.ClinicID, new { @class = "form-control" })
    <br />
    <br />
    @Html.LabelFor(x=>x.ClinicName)
    @Html.TextBoxFor(x=>x.ClinicName, new { @class = "form-control" })
    @Html.ValidationMessageFor(x=>x.ClinicName,"",new { @style="color:red"})
    <br />
    <br />
    @Html.LabelFor(x=>x.ClinicDescription)
    @Html.TextBoxFor(x=>x.ClinicDescription, new { @class = "form-control" })
    <br />
    <br />
    @Html.LabelFor(x=>x.Status)
    @Html.CheckBoxFor(x=>x.Status, new { @class = "form-control" })
    
    <button class="btn btn-info">Save</button>
}

HastaneProjesi/Views/Clinic/Index.cshtml
@inject Microsoft.AspNetCore.Mvc.Localization.IViewLocalizer localizer
@model List<HastaneProjesi.Models.Clinic>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>@Localizer["ClinicList"]</h2>
<br />
<table class="table table-bordered">
    <tr>
        <th>ID</th>
        <th>@Localizer["ClinicName"]</th>
        <th>@Localizer["ClinicDescription"]</th>
        <th>@Localizer["Status"]</th>
        <th>@Localizer["Delete"]</th>
        <th>@Localizer["Update"]</th>
    </tr>
    @foreach (var x in Model)
    {
        <tr>
            <td>@x.ClinicID</td>
            <td>@x.ClinicName</td>
            <td>@x.ClinicDescription</td>
            <td>@x.Status</td>
            <td><a href="/Clinic/ClinicDelete/@x.ClinicID" class="btn btn-danger">Delete</a></td>
            <td><a href="/Clinic/ClinicGet/@x.ClinicID" class="btn btn-success">Update</a></td>
            
        </tr>
    }
</table>
<a href="/Clinic/ClinicAdd/" class="btn btn-primary">@Localizer["AddNewClinic"]</a>